server:
  port: 8082

app:
  mail:
    account-activation-url: http://localhost:8081/api-gateway/api/account/activate
    reset-password-url: http://localhost:8081/api-gateway/api/reset/password
    base-redirect-url: http://localhost:8081/api/link?t=
    activate-account-message-body: |
      <html>
        <body>
          <h2>Welcome to NovaFlow!</h2>
          <p>Thanks for registering. Please click the link below to activate your account:</p>
          <a href="%s" style="display:inline-block;padding:10px 20px;background-color:#4CAF50;color:white;text-decoration:none;border-radius:5px;">Activate Account</a>
          <p>If you didn't register, you can safely ignore this email.</p>
        </body>
      </html>
    reset-password-message-body: |
      <html>
        <body>
          <h2>NovaFlow!</h2>
          <p>Your password has been reset. Please click the link below to confirm that this was you:</p>
          <a href="%s" style="display:inline-block;padding:10px 20px;background-color:#4CAF50;color:white;text-decoration:none;border-radius:5px;">Confirm Reset</a>
          <p>If you didn't request a password reset, you can safely ignore this email.</p>
        </body>
      </html>

spring:
  application:
    name: user-service

  profiles:
    active: dev

  config:
    import: "configserver:http://localhost:7090/"  # Pull config from config server

  cloud:
    config:
      uri: http://localhost:7090  # Location of config server

  liquibase:
    drop-first: false

  jpa:
    show-sql: true

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: ${EMAIL_SMTP_AUTH}
      mail.smtp.starttls.enable: ${EMAIL_STARTTLS}
